Update JS_Cert.js
SHELTER-ZONE/Coder_Cert pull request #1
Opened 2020-04-13 15:07 UTC by kamira

const function

2020-04-13 15:18 UTC, rixinsc requested changes

2020-04-13 15:18 UTC, rixinsc commented on JS_Cert.js
> +  const __get = (userID) => {
Use a more descriptive function name? `__get` is too general.

2020-04-13 15:18 UTC, rixinsc commented on JS_Cert.js
> +}
Any specific reason making this into an arrow function?

2020-04-14 12:18 UTC, kamira commented on JS_Cert.js
> +  const __get = (userID) => {
實際上你跟本拿不到 __get 的 function

2020-04-14 12:18 UTC, kamira commented on JS_Cert.js
> +}
prevent this

2020-04-14 13:08 UTC, rixinsc commented on JS_Cert.js
> +  const __get = (userID) => {
這我知道，只是我會希望內部function的名字可以更有意義一點w

2020-04-14 13:23 UTC, rixinsc commented on JS_Cert.js
> +}
can you elaborate further?

2020-04-14 13:58 UTC, kamira commented on JS_Cert.js
> +}
良好習慣要養成

2020-04-14 14:38 UTC, rixinsc commented on JS_Cert.js
> +}
也不是這樣子的啊…沒事用arrow function幹嘛 👀

2020-07-27 15:29 UTC, closed without merging