修正說明用詞與邏輯
SHELTER-ZONE/Coder_Cert pull request #2
Opened 2020-06-16 09:45 UTC by Titzton

撥空複查 感恩(`・ω・´)!

2020-06-17 10:06 UTC, rixinsc commented on README.md
> +端詳之際，貝利看見門下有10個若隱若現的數字，然而幾組數字並沒有重複，他們覺得這些數字是解開鎖的線索，便轉身向守衛求助。
這樣寫加上`然而幾組數字並沒有重複`這句的話感覺會有點冗餘(?
```suggestion
端詳之際，貝利看見門下有10個若隱若現的數字，他們覺得這些數字是解開鎖的線索，便轉身向守衛求助。
```

2020-06-17 10:12 UTC, rixinsc commented on README.md
> +老守衛給出的代碼中寫入了所有鎖的資料與內部方法，而你只需要幫助貝利完成鑰匙並解開鎖就好。
這樣說明可能會好一點？
```suggestion
老守衛給出的代碼中寫入了所有鎖的資料與內部方法，而你只需要幫助貝利找出每個鎖的解鎖密鑰就好。
```

2020-06-17 10:17 UTC, rixinsc commented on README.md
> +LockSolver當中存有開鎖的必要條件，你必須先將這個類別實例化（初始化）才能使用它。
這樣說明也許會好一些？
```suggestion
LockSolver這個類當中存有開鎖的內部邏輯，你必須先將它實例化（初始化）才能使用它。
```

2020-06-17 10:57 UTC, rixinsc requested changes
一些優化與建議

2020-06-17 10:57 UTC, rixinsc commented on README.md
> +run與slove的關係就好比鎖頭與鑰匙，run是用來傳入slove得出密鑰的，前5組鎖會有錯誤提示。
```suggestion
你需要寫出一個solve函數，用於計算鎖的解鎖密鑰。run方法與solve函數的關係就好比鎖頭與鑰匙，把solve函數傳入run方法之後，run方法將會使用solve函數來計算每個鎖的密鑰，前5組鎖會有錯誤提示。
```

2020-06-17 10:57 UTC, rixinsc commented on README.md
> +當你確認十組密鑰都沒錯的時候，使用getPassword傳入伺服器的創立日期`20180627`（請使用字串型態），他將會回傳一組最終密鑰，得到該密鑰後在[#🔰coder認證](https://discordapp.com/channels/445157253385814016/687603306679369768)頻道輸入`at<語言> <密鑰>`驗證答案。
小改
```suggestion
當你確認十組密鑰都沒錯的時候，將伺服器的創立日期`20180627`（請使用字串型態）傳入getPassword方法並呼叫，它將會回傳一組最終密鑰，得到該密鑰後在[#🔰coder認證](https://discordapp.com/channels/445157253385814016/687603306679369768)頻道輸入`at<語言> <密鑰>`驗證你的答案。
```

2020-06-17 10:57 UTC, rixinsc commented on README.md
> +門鎖會把十組數字（0≦N<10^19）（長度≧2）依序使用字串型態傳入solve函數的token。要讓你手上的這些鑰匙能夠正常運作，你必須使用下面的步驟去撰寫solve函數：
使用≥≤字符而非≧≦，後者用於向量比較，且日常較少使用。[參考](https://en.wikipedia.org/wiki/List_of_mathematical_symbols)
另外，數字並不保證依序傳入，且長度是數字轉為字符串後的字符串長度，故寫在後面。
也有一些闡述上的修改。
```suggestion
呼叫run方法後，LockSolver會把十組數字（0≤n<10^19）使用字串型態（長度≥2）傳入solve函數的第一個參數（一般名為token）。要找出鎖的解鎖密鑰，你必須依照下面的邏輯撰寫solve函數：
```

2020-06-17 10:57 UTC, rixinsc commented on README.md
> +2. 將token的的第一個數字與倒數第二個數字相加後，記錄結果。
```suggestion
2. 將token的第一個數字與倒數第二個數字相加後，記錄結果。
```

2020-06-17 10:57 UTC, rixinsc commented on README.md
> +4. 將以上（1,2,3）步驟得到的結果全部相加後，這將會是你的答案。
```suggestion
4. 將以上（1,2,3）步驟得到的結果全部相加，這將會是你的答案。
```

2020-06-17 10:57 UTC, rixinsc commented on README.md
> +6. 回傳運算出的結果（使用字串型態回傳）。
```suggestion
6. 以字串型態回傳運算出的結果。
```

2020-06-17 10:57 UTC, rixinsc commented on README.md
> +路過的勇者示範了解開一個鎖的過程，他示範的token數字為`12345`：
因形態多變，故這裡不暗示token的形態。
```suggestion
路過的勇者示範了解開一個鎖的過程，他得到的token為`12345`：
```

2020-06-17 10:57 UTC, rixinsc commented on README.md
> +執行LockSolver的run方法，傳入你完成的slove函數，沒有出現錯誤提示之後再使用getPassword方法就能得到最終密鑰了。（請記得先初始化物件才能使用方法）
```suggestion
執行LockSolver的run方法，傳入你的solve函數，最後呼叫getPassword方法就能得到最終密鑰了。（請記得先實例化LockSolver類才使用方法）
```

2020-06-21 14:51 UTC, Titzton commented on README.md
> +執行LockSolver的run方法，傳入你完成的slove函數，沒有出現錯誤提示之後再使用getPassword方法就能得到最終密鑰了。（請記得先初始化物件才能使用方法）
這邊應該是地區用詞差異 
```
（請記得先初始化物件才能使用方法）
```

2020-06-21 14:52 UTC, Titzton commented on README.md
> +路過的勇者示範了解開一個鎖的過程，他示範的token數字為`12345`：
這邊去掉"得到" 不然很容易跟鎖的數字混淆

2020-06-21 15:01 UTC, Titzton commented on README.md
> +老守衛給出的代碼中寫入了所有鎖的資料與內部方法，而你只需要幫助貝利完成鑰匙並解開鎖就好。
這邊我寫得有點歪XDD 加入太多個人意見

2020-06-21 15:01 UTC, Titzton commented on README.md
> +端詳之際，貝利看見門下有10個若隱若現的數字，然而幾組數字並沒有重複，他們覺得這些數字是解開鎖的線索，便轉身向守衛求助。
確實

2020-06-21 15:18 UTC, Titzton commented
再幫我確認一下 上面那些我都看完了~

2020-06-21 15:21 UTC, rixinsc commented on README.md
> +執行LockSolver的run方法，傳入你完成的slove函數，沒有出現錯誤提示之後再使用getPassword方法就能得到最終密鑰了。（請記得先初始化物件才能使用方法）
初始化跟實例化不一樣吧？一個是initialise一個是instantiate 🤔

2020-06-21 15:31 UTC, Titzton commented
問題是實例化較有深度也更正確 但初始化比較好理解吧 意思相差不遠
一般教學幾乎也都是說初始化物件

2020-06-21 15:41 UTC, rixinsc commented on README.md
> +LockSolver當中存有開鎖的必要條件，你必須先用LockSolver把一個物件初始化之後才能使用。
是初始化類而不是初始化物件喔，然後存有的東西我覺得跟條件相比邏輯比較適合？
```suggestion
LockSolver這個類當中存有開鎖的內部邏輯，你必須先初始化LockSolver之後才能使用。  
```

2020-06-21 15:41 UTC, rixinsc commented on README.md
> +執行LockSolver的run方法，傳入你完成的slove函數，沒有出現錯誤提示之後再使用getPassword方法就能得到最終密鑰了。（請記得先初始化物件才能使用方法）
> 問題是實例化較有深度也更正確 但初始化比較好理解吧 意思相差不遠
一般教學幾乎也都是說初始化物件

因為更正確所以才在複述的時候（也就是這裡）選擇一個更精準的用詞，在第10行第一次說明的時候有提到這兩個詞意義接近了。
###### PS: 你其實可以直接在這裡發佈針對一個建議的回復，就不需要回復到討論串上。（這樣會比較不那麼亂）

2020-06-21 15:57 UTC, Titzton commented on README.md
> +LockSolver當中存有開鎖的必要條件，你必須先用LockSolver把一個物件初始化之後才能使用。
對吼 剛剛其他地方改了這邊忘記

2020-06-21 15:58 UTC, rixinsc commented on README.md
> +門鎖會把十組數字（0≤N<10^19）（長度≧2）分別使用字串型態傳入solve函數的token變數。*（這邊數字定義為**由數字組成的一串字**）*
1. 首先修正≧為≥。
1. 傳入的其實是solve函數的第一個變數（不管是否名為token）。
1. 個人不會選擇重新定義數字，因為這可能會引發更多的混淆，直接說明為將數字用字符串形態傳入（字符串形態的數字）會更好。

2020-06-21 15:58 UTC, rixinsc commented on README.md
> +路過的勇者示範了解開一個鎖的過程，他示範的token數字為`12345`：
可以稍微說明如何能跟鎖的數字產生混淆嗎，get不太到你的點 OuO
我這樣改是因為token是動態傳入的所以想說加得到會好一些。

2020-06-21 16:00 UTC, Titzton commented on README.md
> +LockSolver當中存有開鎖的必要條件，你必須先用LockSolver把一個物件初始化之後才能使用。
還是說 盡量避開這兩個詞?

2020-06-21 16:03 UTC, Titzton commented on README.md
> +LockSolver這個類別當中存有開鎖的內部邏輯，你必須建立一個LockSolver屬性的物件之後才能使用。
這樣的話呢

2020-06-21 16:03 UTC, rixinsc commented on README.md
> +LockSolver當中存有開鎖的必要條件，你必須先用LockSolver把一個物件初始化之後才能使用。
嗯？那你要用什麼啊 0.0

2020-06-21 16:04 UTC, rixinsc commented on README.md
> +執行LockSolver的run方法，傳入你完成的slove函數，沒有出現錯誤提示之後再使用getPassword方法就能得到最終密鑰了。（請記得先初始化物件才能使用方法）
嗯…是誤點了嗎？這裡好像還沒resolve呢

2020-06-21 16:07 UTC, rixinsc commented on README.md
> +LockSolver當中存有開鎖的必要條件，你必須先將這個類別實例化（初始化）才能使用它。
Superceded by https://github.com/SHELTER-ZONE/Coder_Cert/pull/2#discussion_r443230873

2020-06-21 16:08 UTC, rixinsc commented on README.md
> +門鎖會把十組數字（0≦N<10^19）（長度≧2）依序使用字串型態傳入solve函數的token。要讓你手上的這些鑰匙能夠正常運作，你必須使用下面的步驟去撰寫solve函數：
Superceded by https://github.com/SHELTER-ZONE/Coder_Cert/pull/2#discussion_r443232540

2020-06-21 16:13 UTC, rixinsc commented on README.md
> +LockSolver這個類別當中存有開鎖的內部邏輯，你必須建立一個LockSolver屬性的物件之後才能使用。
這個只在C, C++這種static typed的語言成立喔，如果在python裡的話通常是不會這樣說的。（i.e. 不會說Foo class的instance為Foo class屬性的object）

2020-06-21 16:15 UTC, rixinsc commented on README.md
> +端詳之際，貝利看見門下有10個若隱若現的數字，然而幾組數字並沒有重複，他們覺得這些數字是解開鎖的線索，便轉身向守衛求助。
這個好像還沒有改到呢 👀

2020-06-27 17:55 UTC, rixinsc requested changes
一些地方多出了空格

2020-06-27 17:55 UTC, rixinsc commented on README.md
> +你需要寫出一個solve函數，用於計算鎖的解鎖密鑰。run方法與solve函數的關係就好比鎖頭與鑰匙，把solve函數傳入run方法之後，run方法將會使用solve函數來計算出每個鎖的密鑰，前5組鎖會有錯誤提示。
多出了空格
```suggestion
老守衛給出的代碼中寫入了所有鎖的資料與內部方法，而你只需要幫助貝利找出每個鎖的解鎖密鑰就好。
LockSolver這個類別當中存有開鎖的內部邏輯，你必須將LockSolver實例化之後才能使用。
你需要寫出一個solve函數，用於計算鎖的解鎖密鑰。run方法與solve函數的關係就好比鎖頭與鑰匙，把solve函數傳入run方法之後，run方法將會使用solve函數來計算出每個鎖的密鑰，前5組鎖會有錯誤提示。
```

2020-06-27 17:55 UTC, rixinsc commented on README.md
> +6. 以字串型態回傳運算出的結果。
多出了空格
```suggestion
6. 以字串型態回傳運算出的結果。
```

2020-06-27 17:55 UTC, rixinsc commented on README.md
> +執行LockSolver的run方法，傳入你完成的slove函數，沒有出現錯誤提示之後再使用getPassword方法就能得到最終密鑰了。（記得先將LockSolver實例化）
```suggestion
執行LockSolver的run方法，傳入你完成的solve函數，沒有出現錯誤提示之後再使用getPassword方法就能得到最終密鑰了。（記得先將LockSolver實例化）
```

2020-06-27 17:57 UTC, rixinsc commented on README.md
> +門鎖會把十組數字（0≤N<10^19）（長度≧2）分別使用字串型態傳入solve函數的token變數。*（這邊數字定義為**由數字組成的一串字**）*
這個還沒有修正呢？有其他意見的話可以留言討論喔~

2020-06-27 18:00 UTC, rixinsc commented
剛再看過了一次，問題應該就只剩 https://github.com/SHELTER-ZONE/Coder_Cert/pull/2#discussion_r446550790 了~

2020-07-09 15:44 UTC, rixinsc requested changes

2020-07-09 15:44 UTC, rixinsc commented on README.md
> +門鎖會把十組數字（0≤N<10^19）（長度≥2）分別使用字串型態傳入solve函數的第一個變數(token)。*（這邊數字泛指**由數字組成的一串字**）*
如果改這樣如何？👀
```suggestion
門鎖會把十組數字（0≤N<10^19）（長度≥2）分別使用字串型態傳入solve函數的第一個變數（token）。
```

2020-07-09 15:45 UTC, rixinsc commented on README.md
> +門鎖會把十組數字（0≤N<10^19）（長度≧2）分別使用字串型態傳入solve函數的token變數。*（這邊數字定義為**由數字組成的一串字**）*
Superceded by https://github.com/SHELTER-ZONE/Coder_Cert/pull/2#discussion_r452314803

2020-07-16 13:20 UTC, Titzton commented
這樣整體看下來還有哪些需要提出來修正的

2020-07-16 13:24 UTC, rixinsc commented
還有這個喔~
https://github.com/SHELTER-ZONE/Coder_Cert/pull/2#discussion_r452314803

2020-07-16 16:18 UTC, Titzton commented
這樣呢 
門鎖會把十組數字（0≤N<10^19）（長度≥2）分別使用**字串型態**傳入solve函數的第一個變數(token)。

2020-07-16 16:26 UTC, rixinsc approved these changes
LGTM

2020-07-16 16:35 UTC, merged